# Generated by Django 3.2.16 on 2022-12-12 15:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('title', models.CharField(max_length=1000, verbose_name='название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Опубликован')),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('image', models.ImageField(blank=True, upload_to='company/image', validators=[django.core.validators.validate_image_file_extension], verbose_name='картинка')),
                ('description', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
    ]
